// databaseConfig.js
module.exports = {
    A: {
      database: 'A',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    B: {
      database: 'B',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    C: {
      database: 'C',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    Tallahassee: {
      database: 'Tallahassee',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    Ashe: {
        database: 'Ashe',
        username: 'root',
        password: 'root',
        host: 'localhost',
        dialect: 'mysql',
      },
    CCG: {
      database: 'CCG',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    master_email: {
      database: 'master_email',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    AIG_wound: {
      database: 'AIG_wound',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    AIG_DDC: {
      database: 'AIG_DDC',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    AIG_HVLC: {
      database: 'AIG_HVLC',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
    AIG_PSC: {
      database: 'AIG_PSC',
      username: 'root',
      password: 'root',
      host: 'localhost',
      dialect: 'mysql',
    },
  };
  